import { Language, UIContent } from './types';

export const UI_TRANSLATIONS: Record<Language, UIContent> = {
  [Language.ENGLISH]: {
    title: "Shasyarakshak",
    subtitle: "Crop Protector for Odisha",
    uploadButton: "Analyze Crop",
    analyzing: "Analyzing crop health...",
    results: "Diagnosis Report",
    severity: "Severity",
    confidence: "AI Confidence",
    organic: "Organic Solutions",
    chemical: "Chemical Controls",
    kvkContact: "Expert Support (KVK)",
    kvkLinkText: "Find nearest KVK Center",
    selectImage: "Upload Photo",
    takePhoto: "Take Photo",
    retry: "Analyze Another",
    home: "Home",
    kvkSearchLabel: "Find your nearest Krishi Vigyan Kendra",
    kvkSearchPlaceholder: "Search by District (e.g., Khordha)",
    phone: "Phone",
    email: "Email",
    address: "Address",
    callNow: "Call Now",
    noResults: "No KVK found for this district.",
    savedCenter: "My Preferred KVK",
    save: "Set as my KVK",
    remove: "Remove",
    navHome: "Home",
    navHistory: "History",
    navWeather: "Weather",
    navSettings: "Settings",
    weatherTitle: "Today's Field Weather",
    weatherHumidity: "Humidity",
    weatherWind: "Wind",
    weatherRainChance: "Rain Chance",
    weatherSpraySafe: "Good conditions for spraying",
    weatherSprayUnsafe: "Avoid spraying — rain or high wind expected",
    weatherLoading: "Fetching local weather...",
    weatherDenied: "Location access denied. Enable location to see local weather.",
    weatherRetry: "Try Again",
    historyTitle: "Scan History",
    historyEmpty: "No scans yet",
    historyEmptyHint: "Your analyzed crops will appear here for future reference.",
    historyClearAll: "Clear All",
    historyDelete: "Delete",
    historyConfirmClear: "Delete all saved scan history?",
    cropSelectLabel: "Select crop type (optional)",
    cropPaddy: "Paddy",
    cropMillet: "Millet",
    cropAuto: "Auto-detect",
    listen: "Listen",
    stopListening: "Stop",
    share: "Share Report",
    shareCopied: "Report copied to clipboard!",
    settingsTitle: "Settings",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    offlineNotice: "You are offline. Some features may be limited.",
    aboutApp: "About Shasyarakshak",
    clearData: "Clear all app data",
    appVersion: "Version",
    toolsTitle: "AI Farming Tools",
    toolFarmDoctor: "AI Farm Doctor",
    toolFarmDoctorDesc: "Personalized, proactive crop risk alerts",
    toolVoiceAssistant: "Voice Assistant",
    toolVoiceAssistantDesc: "Ask any farming question by voice or text",
    toolCropCalendar: "Crop Calendar",
    toolCropCalendarDesc: "Fertilizer, irrigation & harvest timeline",
    toolProfitCalculator: "Profit Calculator",
    toolProfitCalculatorDesc: "Estimate income, cost and break-even",
    toolFieldMonitor: "Field Monitor",
    toolFieldMonitorDesc: "Mark your field for future satellite tracking",
    back: "Back",
    farmDoctorTitle: "AI Farm Doctor",
    farmProfileSetup: "Set Up Your Farm Profile",
    farmProfileDistrict: "District",
    farmProfileSowingDate: "Sowing Date",
    farmProfileSoilType: "Soil Type",
    farmProfilePastIssues: "Past Disease History (optional)",
    farmProfilePastIssuesPlaceholder: "e.g. Blast affected last season",
    farmProfileSave: "Save Profile",
    soilAlluvial: "Alluvial",
    soilLaterite: "Laterite",
    soilClay: "Clay",
    soilSandy: "Sandy",
    soilUnknown: "Not Sure",
    farmDoctorGenerating: "Analyzing your farm's risk factors...",
    farmDoctorRefresh: "Refresh Advisory",
    farmDoctorNoProfile: "Set up your farm profile to get personalized, proactive alerts based on your crop's age, soil, and this week's weather.",
    farmDoctorEditProfile: "Edit Profile",
    riskLow: "Low Risk",
    riskMedium: "Medium Risk",
    riskHigh: "High Risk",
    voiceAssistantTitle: "Ask the AI Assistant",
    voiceAssistantPlaceholder: "Type or speak your farming question...",
    voiceAssistantListening: "Listening...",
    voiceAssistantSend: "Send",
    voiceAssistantMicUnsupported: "Voice input isn't supported on this browser — you can still type your question.",
    voiceAssistantThinking: "Thinking...",
    cropCalendarTitle: "AI Crop Calendar",
    cropCalendarCropName: "Crop Name",
    cropCalendarCropPlaceholder: "e.g. Paddy, Ragi, Bajra",
    cropCalendarSowingDate: "Sowing Date",
    cropCalendarGenerate: "Generate Calendar",
    cropCalendarGenerating: "Building your crop timeline...",
    cropCalendarHarvestEstimate: "Estimated Harvest",
    catFertilizer: "Fertilizer",
    catIrrigation: "Irrigation",
    catPest: "Pest Alert",
    catHarvest: "Harvest",
    catOther: "Other",
    profitTitle: "Crop Profit Calculator",
    profitLandArea: "Land Area (acres)",
    profitCrop: "Crop",
    profitExpectedYield: "Expected Yield (quintals/acre)",
    profitPricePerQuintal: "Expected Price (₹/quintal)",
    profitFertilizerCost: "Fertilizer Cost (₹)",
    profitLabourCost: "Labour Cost (₹)",
    profitOtherCost: "Other Costs (₹)",
    profitCalculate: "Calculate Profit",
    profitTotalYield: "Total Yield",
    profitTotalIncome: "Total Income",
    profitTotalInvestment: "Total Investment",
    profitEstimate: "Estimated Profit",
    profitBreakEvenYield: "Break-even Yield Needed",
    profitBreakEvenPrice: "Break-even Price Needed",
    fieldMonitorTitle: "Field Monitor",
    fieldMonitorIntro: "Mark your field's location now so future satellite-based health, moisture, and vegetation monitoring can use it automatically — this feature is on our roadmap.",
    fieldMonitorSaveLocation: "Save My Current Location",
    fieldMonitorSaved: "Field location saved",
    fieldMonitorRoadmap: "Coming soon: vegetation health (NDVI), soil moisture, and dry-patch alerts using satellite imagery."
  },
  [Language.ODIA]: {
    title: "ଶସ୍ୟରକ୍ଷକ",
    subtitle: "ଓଡିଶାର କୃଷକମାନଙ୍କ ପାଇଁ",
    uploadButton: "ଫସଲ ପରୀକ୍ଷା କରନ୍ତୁ",
    analyzing: "ଫସଲ ରୋଗ ବିଶ୍ଳେଷଣ ଚାଲିଛି...",
    results: "ରୋଗ ନିର୍ଣ୍ଣୟ ରିପୋର୍ଟ",
    severity: "ପ୍ରଭାବ",
    confidence: "ନିଶ୍ଚିତତା",
    organic: "ଜୈବିକ ଉପଚାର",
    chemical: "ରାସାୟନିକ ନିୟନ୍ତ୍ରଣ",
    kvkContact: "ବିଶେଷଜ୍ଞ ସହାୟତା (KVK)",
    kvkLinkText: "ନିକଟସ୍ଥ କୃଷି ବିଜ୍ଞାନ କେନ୍ଦ୍ର (KVK)",
    selectImage: "ଫଟୋ ଅପଲୋଡ୍ କରନ୍ତୁ",
    takePhoto: "ଫଟୋ ଉଠାନ୍ତୁ",
    retry: "ଅନ୍ୟ ଏକ ପରୀକ୍ଷା କରନ୍ତୁ",
    home: "ମୂଳ ପୃଷ୍ଠା",
    kvkSearchLabel: "ଆପଣଙ୍କ ନିକଟସ୍ଥ କୃଷି ବିଜ୍ଞାନ କେନ୍ଦ୍ର ଖୋଜନ୍ତୁ",
    kvkSearchPlaceholder: "ଜିଲ୍ଲା ନାମ ଲେଖନ୍ତୁ (ଯେପରିକି ଖୋର୍ଦ୍ଧା)",
    phone: "ଫୋନ୍",
    email: "ଇମେଲ୍",
    address: "ଠିକଣା",
    callNow: "କଲ୍ କରନ୍ତୁ",
    noResults: "ଏହି ଜିଲ୍ଲା ପାଇଁ କୌଣସି KVK ମିଳିଲା ନାହିଁ।",
    savedCenter: "ମୋ ପସନ୍ଦର KVK",
    save: "ମୋ କେନ୍ଦ୍ର ଭାବେ ବାଛନ୍ତୁ",
    remove: "ହଟାନ୍ତୁ",
    navHome: "ମୂଳ ପୃଷ୍ଠା",
    navHistory: "ପୂର୍ବ ତଥ୍ୟ",
    navWeather: "ପାଣିପାଗ",
    navSettings: "ସେଟିଂସ୍",
    weatherTitle: "ଆଜିର କ୍ଷେତ ପାଣିପାଗ",
    weatherHumidity: "ଆର୍ଦ୍ରତା",
    weatherWind: "ପବନ",
    weatherRainChance: "ବର୍ଷାର ସମ୍ଭାବନା",
    weatherSpraySafe: "ସ୍ପ୍ରେ କରିବା ପାଇଁ ଉପଯୁକ୍ତ ପାଣିପାଗ",
    weatherSprayUnsafe: "ସ୍ପ୍ରେ କରନ୍ତୁ ନାହିଁ — ବର୍ଷା କିମ୍ବା ଅଧିକ ପବନ ସମ୍ଭାବନା",
    weatherLoading: "ସ୍ଥାନୀୟ ପାଣିପାଗ ଆଣୁଛି...",
    weatherDenied: "ଲୋକେସନ୍ ଅନୁମତି ମିଳିଲା ନାହିଁ। ପାଣିପାଗ ଦେଖିବାକୁ ଲୋକେସନ୍ ଅନ୍ କରନ୍ତୁ।",
    weatherRetry: "ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ",
    historyTitle: "ପୂର୍ବ ପରୀକ୍ଷା ତାଲିକା",
    historyEmpty: "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ପରୀକ୍ଷା ନାହିଁ",
    historyEmptyHint: "ଆପଣଙ୍କ ବିଶ୍ଳେଷିତ ଫସଲ ଏଠାରେ ଦେଖାଯିବ।",
    historyClearAll: "ସବୁ ଲିଭାନ୍ତୁ",
    historyDelete: "ଲିଭାନ୍ତୁ",
    historyConfirmClear: "ସମସ୍ତ ପୂର୍ବ ତଥ୍ୟ ଲିଭାଇବେ କି?",
    cropSelectLabel: "ଫସଲ ପ୍ରକାର ବାଛନ୍ତୁ (ଇଚ୍ଛାଧୀନ)",
    cropPaddy: "ଧାନ",
    cropMillet: "ମାଣ୍ଡିଆ",
    cropAuto: "ସ୍ୱୟଂ-ଚିହ୍ନଟ",
    listen: "ଶୁଣନ୍ତୁ",
    stopListening: "ବନ୍ଦ କରନ୍ତୁ",
    share: "ରିପୋର୍ଟ ସେୟାର୍ କରନ୍ତୁ",
    shareCopied: "ରିପୋର୍ଟ କପି ହୋଇଗଲା!",
    settingsTitle: "ସେଟିଂସ୍",
    darkMode: "ଡାର୍କ ମୋଡ୍",
    lightMode: "ଲାଇଟ୍ ମୋଡ୍",
    offlineNotice: "ଆପଣ ଅଫଲାଇନ୍ ଅଛନ୍ତି। କିଛି ସୁବିଧା ସୀମିତ ହୋଇପାରେ।",
    aboutApp: "ଶସ୍ୟରକ୍ଷକ ବିଷୟରେ",
    clearData: "ସମସ୍ତ ଆପ୍ ତଥ୍ୟ ଲିଭାନ୍ତୁ",
    appVersion: "ସଂସ୍କରଣ",
    toolsTitle: "AI କୃଷି ସାଧନ",
    toolFarmDoctor: "AI ଫାର୍ମ ଡାକ୍ତର",
    toolFarmDoctorDesc: "ବ୍ୟକ୍ତିଗତ, ପୂର୍ବାନୁମାନିକ ଫସଲ ବିପଦ ସତର୍କତା",
    toolVoiceAssistant: "ଭଏସ୍ ସହାୟକ",
    toolVoiceAssistantDesc: "ସ୍ୱର କିମ୍ବା ଲେଖି ଯେକୌଣସି ପ୍ରଶ୍ନ ପଚାରନ୍ତୁ",
    toolCropCalendar: "ଫସଲ କ୍ୟାଲେଣ୍ଡର",
    toolCropCalendarDesc: "ସାର, ଜଳସେଚନ ଏବଂ ଅମଳ ସମୟସୂଚୀ",
    toolProfitCalculator: "ଲାଭ କାଲକୁଲେଟର",
    toolProfitCalculatorDesc: "ଆୟ, ଖର୍ଚ୍ଚ ଏବଂ break-even ଆକଳନ",
    toolFieldMonitor: "କ୍ଷେତ ମନିଟର",
    toolFieldMonitorDesc: "ଭବିଷ୍ୟତ ଉପଗ୍ରହ ନଜରକୁ ଆପଣଙ୍କ କ୍ଷେତ ଚିହ୍ନଟ କରନ୍ତୁ",
    back: "ପଛକୁ",
    farmDoctorTitle: "AI ଫାର୍ମ ଡାକ୍ତର",
    farmProfileSetup: "ଆପଣଙ୍କ ଫାର୍ମ ପ୍ରୋଫାଇଲ୍ ସେଟ୍ କରନ୍ତୁ",
    farmProfileDistrict: "ଜିଲ୍ଲା",
    farmProfileSowingDate: "ବୁଣିବା ତାରିଖ",
    farmProfileSoilType: "ମାଟି ପ୍ରକାର",
    farmProfilePastIssues: "ପୂର୍ବ ରୋଗ ଇତିହାସ (ଇଚ୍ଛାଧୀନ)",
    farmProfilePastIssuesPlaceholder: "ଉଦା: ଗତ ଥର ବ୍ଲାଷ୍ଟ ଆକ୍ରମଣ",
    farmProfileSave: "ପ୍ରୋଫାଇଲ୍ ସେଭ୍ କରନ୍ତୁ",
    soilAlluvial: "ପଲିମାଟି",
    soilLaterite: "ଲାଟେରାଇଟ୍",
    soilClay: "ଚିକଣମାଟି",
    soilSandy: "ବାଲିମାଟି",
    soilUnknown: "ଜଣା ନାହିଁ",
    farmDoctorGenerating: "ଆପଣଙ୍କ କ୍ଷେତର ବିପଦ ବିଶ୍ଳେଷଣ ହେଉଛି...",
    farmDoctorRefresh: "ପରାମର୍ଶ ପୁନଃତାଜା କରନ୍ତୁ",
    farmDoctorNoProfile: "ଫସଲର ବୟସ, ମାଟି ଏବଂ ଏହି ସପ୍ତାହର ପାଣିପାଗ ଆଧାରରେ ବ୍ୟକ୍ତିଗତ ସତର୍କତା ପାଇବାକୁ ଆପଣଙ୍କ ଫାର୍ମ ପ୍ରୋଫାଇଲ୍ ସେଟ୍ କରନ୍ତୁ।",
    farmDoctorEditProfile: "ପ୍ରୋଫାଇଲ୍ ଏଡିଟ୍ କରନ୍ତୁ",
    riskLow: "କମ୍ ବିପଦ",
    riskMedium: "ମଧ୍ୟମ ବିପଦ",
    riskHigh: "ଅଧିକ ବିପଦ",
    voiceAssistantTitle: "AI ସହାୟକଙ୍କୁ ପଚାରନ୍ତୁ",
    voiceAssistantPlaceholder: "ଆପଣଙ୍କ କୃଷି ପ୍ରଶ୍ନ ଲେଖନ୍ତୁ କିମ୍ବା କୁହନ୍ତୁ...",
    voiceAssistantListening: "ଶୁଣୁଛି...",
    voiceAssistantSend: "ପଠାନ୍ତୁ",
    voiceAssistantMicUnsupported: "ଏହି ବ୍ରାଉଜରରେ ଭଏସ୍ ଇନପୁଟ୍ ସମର୍ଥିତ ନାହିଁ — ଆପଣ ଲେଖି ପଚାରିପାରିବେ।",
    voiceAssistantThinking: "ଚିନ୍ତା କରୁଛି...",
    cropCalendarTitle: "AI ଫସଲ କ୍ୟାଲେଣ୍ଡର",
    cropCalendarCropName: "ଫସଲ ନାମ",
    cropCalendarCropPlaceholder: "ଉଦା: ଧାନ, ମାଣ୍ଡିଆ, ବାଜରା",
    cropCalendarSowingDate: "ବୁଣିବା ତାରିଖ",
    cropCalendarGenerate: "କ୍ୟାଲେଣ୍ଡର ତିଆରି କରନ୍ତୁ",
    cropCalendarGenerating: "ଆପଣଙ୍କ ଫସଲ ସମୟସୂଚୀ ତିଆରି ହେଉଛି...",
    cropCalendarHarvestEstimate: "ଆକଳିତ ଅମଳ",
    catFertilizer: "ସାର",
    catIrrigation: "ଜଳସେଚନ",
    catPest: "କୀଟ ସତର୍କତା",
    catHarvest: "ଅମଳ",
    catOther: "ଅନ୍ୟାନ୍ୟ",
    profitTitle: "ଫସଲ ଲାଭ କାଲକୁଲେଟର",
    profitLandArea: "ଜମି କ୍ଷେତ୍ର (ଏକର)",
    profitCrop: "ଫସଲ",
    profitExpectedYield: "ଆଶାକରାଯାଉଥିବା ଅମଳ (କ୍ୱିଣ୍ଟାଲ/ଏକର)",
    profitPricePerQuintal: "ଆଶାକରାଯାଉଥିବା ମୂଲ୍ୟ (₹/କ୍ୱିଣ୍ଟାଲ)",
    profitFertilizerCost: "ସାର ଖର୍ଚ୍ଚ (₹)",
    profitLabourCost: "ମଜୁରି ଖର୍ଚ୍ଚ (₹)",
    profitOtherCost: "ଅନ୍ୟାନ୍ୟ ଖର୍ଚ୍ଚ (₹)",
    profitCalculate: "ଲାଭ ଗଣନା କରନ୍ତୁ",
    profitTotalYield: "ମୋଟ ଅମଳ",
    profitTotalIncome: "ମୋଟ ଆୟ",
    profitTotalInvestment: "ମୋଟ ବିନିଯୋଗ",
    profitEstimate: "ଆକଳିତ ଲାଭ",
    profitBreakEvenYield: "Break-even ପାଇଁ ଆବଶ୍ୟକ ଅମଳ",
    profitBreakEvenPrice: "Break-even ପାଇଁ ଆବଶ୍ୟକ ମୂଲ୍ୟ",
    fieldMonitorTitle: "କ୍ଷେତ ମନିଟର",
    fieldMonitorIntro: "ଭବିଷ୍ୟତର ଉପଗ୍ରହ-ଆଧାରିତ ସ୍ୱାସ୍ଥ୍ୟ, ଆର୍ଦ୍ରତା ଏବଂ ବୃକ୍ଷାବରଣ ନଜର ପାଇଁ ଆପଣଙ୍କ କ୍ଷେତର ସ୍ଥାନ ବର୍ତ୍ତମାନ ସେଭ୍ କରନ୍ତୁ — ଏହା ଆମର ଭବିଷ୍ୟତ ଯୋଜନାରେ ଅଛି।",
    fieldMonitorSaveLocation: "ମୋ ବର୍ତ୍ତମାନ ସ୍ଥାନ ସେଭ୍ କରନ୍ତୁ",
    fieldMonitorSaved: "କ୍ଷେତ ସ୍ଥାନ ସେଭ୍ ହୋଇଗଲା",
    fieldMonitorRoadmap: "ଶୀଘ୍ର ଆସୁଛି: ଉପଗ୍ରହ ଚିତ୍ର ବ୍ୟବହାର କରି ବୃକ୍ଷାବରଣ ସ୍ୱାସ୍ଥ୍ୟ (NDVI), ମାଟି ଆର୍ଦ୍ରତା ଏବଂ ଶୁଷ୍କ ସ୍ଥାନ ସତର୍କତା।"
  }
};

export const SAMPLE_IMAGES = [
  "https://picsum.photos/seed/paddy/400/300",
  "https://picsum.photos/seed/millet/400/300"
];